// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHxtWLMhmcjmPu6fw8U7lUBsVYqCYr794',
    appId: '1:704887122823:web:5f70b8a2fda580ac0e4122',
    messagingSenderId: '704887122823',
    projectId: 'archi-link-7c8da',
    authDomain: 'archi-link-7c8da.firebaseapp.com',
    storageBucket: 'archi-link-7c8da.firebasestorage.app',
    measurementId: 'G-L1K8ZX8FFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi6LVQ8N1xicKcHbJTkl2-EC8mv4f1Mcw',
    appId: '1:704887122823:android:869d1053b917c2aa0e4122',
    messagingSenderId: '704887122823',
    projectId: 'archi-link-7c8da',
    storageBucket: 'archi-link-7c8da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPvM4kqyKrdnpx46zoMlQ5We9xez9H9eU',
    appId: '1:704887122823:ios:043ad4ee195755250e4122',
    messagingSenderId: '704887122823',
    projectId: 'archi-link-7c8da',
    storageBucket: 'archi-link-7c8da.firebasestorage.app',
    iosBundleId: 'com.example.archilink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPvM4kqyKrdnpx46zoMlQ5We9xez9H9eU',
    appId: '1:704887122823:ios:043ad4ee195755250e4122',
    messagingSenderId: '704887122823',
    projectId: 'archi-link-7c8da',
    storageBucket: 'archi-link-7c8da.firebasestorage.app',
    iosBundleId: 'com.example.archilink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHxtWLMhmcjmPu6fw8U7lUBsVYqCYr794',
    appId: '1:704887122823:web:737963b8390a88c90e4122',
    messagingSenderId: '704887122823',
    projectId: 'archi-link-7c8da',
    authDomain: 'archi-link-7c8da.firebaseapp.com',
    storageBucket: 'archi-link-7c8da.firebasestorage.app',
    measurementId: 'G-V0MPZJXE1V',
  );
}
